// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWKlHU4mhpHC_X8OaJzVs52DGqOpvF2Y',
    appId: '1:344562081989:web:8010435c9f0c9d5ed350ac',
    messagingSenderId: '344562081989',
    projectId: 'practice-1-c6265',
    authDomain: 'practice-1-c6265.firebaseapp.com',
    storageBucket: 'practice-1-c6265.appspot.com',
    measurementId: 'G-MPH9FLW5WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy2DNIped0rFU7mhaKVKh8qzTgBDJFqp8',
    appId: '1:344562081989:android:a2d685d303170bebd350ac',
    messagingSenderId: '344562081989',
    projectId: 'practice-1-c6265',
    storageBucket: 'practice-1-c6265.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcNmd7zOQ3fuySTptEzBFfORdwQxQrv5Y',
    appId: '1:344562081989:ios:508bbfdd38217fe0d350ac',
    messagingSenderId: '344562081989',
    projectId: 'practice-1-c6265',
    storageBucket: 'practice-1-c6265.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcNmd7zOQ3fuySTptEzBFfORdwQxQrv5Y',
    appId: '1:344562081989:ios:508bbfdd38217fe0d350ac',
    messagingSenderId: '344562081989',
    projectId: 'practice-1-c6265',
    storageBucket: 'practice-1-c6265.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWKlHU4mhpHC_X8OaJzVs52DGqOpvF2Y',
    appId: '1:344562081989:web:6ee5ded1a4cce86bd350ac',
    messagingSenderId: '344562081989',
    projectId: 'practice-1-c6265',
    authDomain: 'practice-1-c6265.firebaseapp.com',
    storageBucket: 'practice-1-c6265.appspot.com',
    measurementId: 'G-PN0DFL85DT',
  );
}
